pipeline {
    agent any

    stages {
        stage('create docker image') {
            steps {
                sh 'mvn package -DskipTests'
                sh 'pwd'
                sh 'docker build .'
            }
        }
    }
}
