pipeline {
    agent any

    stages {
        stage('create docker image') {
            steps {
                sh 'mvn package -DskipTests'
                sh 'docker build -t pron9/vkr .'
            }
        }
    }
}
